### ISSUE TITLE
Multiple gallery objects on one page conflict

### ISSUE THREAD

**Issue by c-fitzmaurice** [RobinCK/vue-gallery#11]
When there are multiple `<gallery>` instances on a page, it breaks. The gallery opens, but will not display the images.

Below is my set up, you can see the gallery has an array of images too.

![image](https://user-images.githubusercontent.com/3401771/34841104-17f21f4e-f6d5-11e7-9484-a074a57d2016.png)

**Comment by khoanguyen96** [comment]
Hey, it's probably because multiple `<gallery>` instances all have the same `id`. Try setting the `id` for each `<gallery>` to something unique via it's `id` prop.

``` html
<gallery id="some-string" />
```

**Comment by c-fitzmaurice** [comment]
You are awesome! Worked like a charm, thanks!!
