### ISSUE TITLE
Data Description

### ISSUE THREAD

**Issue by renatodolce** [RobinCK/vue-gallery#12]
Hello everyone! I would like you to implement this improvement or explain how to do it, if there is one already.

https://github.com/blueimp/Gallery#additional-gallery-elements

**Comment by khoanguyen96** [comment]
Hey @renatodolce,

I had to change a couple of things with a fork to add the description for each image.

Here's a [JSFiddle](https://jsfiddle.net/khoanguyen96/92L3b7jf/) to tinker with.

You can find the changes I made in [update-description branch](https://github.com/khoanguyen96/vue-gallery/tree/add-description) of my fork.

If you want (and once I have some time) I can make a PR and then @RobinCK can merge it in if he wants this.

**Comment by renatodolce** [comment]
@khoanguyen96 Thank you, it was excellent! Just take a doubt, have a delay in the slide exchange, know if you have how to take ?? look at the gif I made on top of your [JSFiddle](https://jsfiddle.net/92L3b7jf/12/)

![vuegallerydescription](https://user-images.githubusercontent.com/5089350/35914134-57426432-0be9-11e8-8779-52d45aed61c1.gif)

**Comment by renatodolce** [comment]
I was able to solve it, you were calling on the onslideend I changed it to call on the onslide only, then it worked. thank you ;-)

**Comment by khoanguyen96** [comment]
Ah sorry that's my bad. My original intention was to call onslide, regardless I'm glad you figured it out!

Should I prep a PR? Or are you good for now?

Cheers!

**Comment by renatodolce** [comment]
No problem, good thing we found out 💪
Feel free to PR 😄
Hugs!
