### ISSUE TITLE
How to make infinite gallery? 

### ISSUE THREAD

**Issue by vavan19** [RobinCK/vue-gallery#127]
When I scroll the images to the right I want to loop through the images endlessly. Like after the last one goes the first one and the loop starts again. Is it possible to achieve with options setup? Or any other way?

**Comment by RobinCK** [comment]
please see https://github.com/RobinCK/vue-gallery#props and https://github.com/blueimp/Gallery#options

**Comment by vavan19** [comment]
@RobinCK please advice which one refers to "infinite" property. I have not found anything that referts to it  by myself. Great thanks for you help!!!

**Comment by RobinCK** [comment]
```
// Allow continuous navigation, moving from last to first
// and from first to last slide:
continuous: true,
```
