### ISSUE TITLE
Problem with video slider

### ISSUE THREAD

**Issue by demokrrat** [RobinCK/vue-gallery#14]
Hi, I'm having problems with the slider (_vue-gallery_)
I'm trying to make a gallery of video files from YouTube and it does not work (_shown in the screenshot_). As I understand it it automatically defines using "options" that it is a view or picture and
substitute the desired template in the slide. Maybe I forgot to connect something?
Thankful in advance for the help.

![error1](https://user-images.githubusercontent.com/20026934/36737586-169772f0-1be4-11e8-976d-fd59f4e6cb1d.png)

![code1](https://user-images.githubusercontent.com/20026934/36737573-125db334-1be4-11e8-8345-5cbfccbb514a.png)

**Comment by RobinCK** [comment]
hi @demokrrat 
See my [example](https://jsfiddle.net/Robin_ck/rpfmb1wq/) 

Pay attention to the connected resources and their sequence
