### ISSUE TITLE
local images path not working

### ISSUE THREAD

**Issue by nothinghalosix** [RobinCK/vue-gallery#140]
i try few path variants. my image folder is assets/images/products/wiener-linien-verlaengerung/RL-U1-7448.jpg

in the inspector: GET http://localhost:8080/assets/images/products/wiener-linien-verlaengerung/RL-U1-7448.jpg 404 (Not Found)

`data() {
        return {
            allImages: {
                1: {
                imgsArr: [
                    'assets/images/products/wiener-linien-verlaengerung/RL-U1-7448.jpg',
                    'https://dummyimage.com/1500/575757/ffffff&text=gallery-1+2'
                ],
                index: null
                },
                2: {
                imgsArr: [
                    'https://dummyimage.com/1500/608566/ffffff&text=gallery-2+1',
                    'https://dummyimage.com/1500/608566/ffffff&text=gallery-2+2'
                ],
                index: null
                }
            }
        }
    }`

**Comment by spelbreker** [comment]
in the imgsArray is missing a part of the url ('assets/images/products/wiener-linien-verlaengerung/RL-U1-7448.jpg') 

8080 is not a default web port 80 or 433 is. if port is different, you must add the complete url with port.

**Comment by nothinghalosix** [comment]
i changed the url and render from the live url
