### ISSUE TITLE
Vue gallery 'options' props

### ISSUE THREAD

**Issue by fsfj** [RobinCK/vue-gallery#15]
Hello,

How to can i use 'options' props?

Thanks Vue-Gallery for the great work!

**Comment by RobinCK** [comment]
```html
<gallery :images="images" :index="index" @close="index = null" :options="{optionProp: 'Option value'}"></gallery>
```

Please see my [example](https://fiddle.jshell.net/Robin_ck/djqcrm8m/?utm_source=website&utm_medium=embed&utm_campaign=djqcrm8m)

**Comment by fsfj** [comment]
will try this. thank you
