### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by FabianEllenberger** [RobinCK/vue-gallery#18]
Tried to implement vue-gellery into my nuxt.js app and got the `Maximum call stack size exceeded` error. I'm using it as a plugin as mentioned here https://github.com/RobinCK/vue-gallery/issues/3 and have the basic options as shown in the readme. Did any of you had the same error or knows what I'm could be doing wrong here (code below)? Thanks! 🙏🏻

```javascript
<script>

export default {
  name: 'Gallery',
  data: () => ({
    index: null,
    images: [
      'https://dummyimage.com/800/ffffff/000000',
      'https://dummyimage.com/1600/ffffff/000000',
      'https://dummyimage.com/1280/000000/ffffff',
      'https://dummyimage.com/400/000000/ffffff'
    ]
  })
}
</script>

<style src='./Gallery.scss' lang='scss'></style>

<template>
  <div class="Gallery">
    <gallery :images="images" :index="index" @close="index = null"></gallery>
    <div
      class="Gallery__image"
      v-for="(image, imageIndex) in images"
      :key="imageIndex"
      @click="index = imageIndex"
      :style="{ backgroundImage: 'url(' + image + ')', width: '300px', height: '200px' }">
    </div>
  </div>
</template>
```

**Comment by RobinCK** [comment]
Sorry, but I did not work with nuxt.js
Maybe the guys will prompt @rlam3 @lomholdt
Just advise to see: https://github.com/RobinCK/vue-gallery/pull/7

**Comment by lomholdt** [comment]
It seems weird. It's working perfectly for me. I can't see any problems with the provided code example. Are you sure the problem comes from vue-gallery?

**Comment by FabianEllenberger** [comment]
@lomholdt that was what i was thinking aswell, but as soon as i add the component `<gallery>` even with or without any props the error occurs. I'll keep on investigating and will write my update here if i figured something out

**Comment by RobinCK** [comment]
Thanks

**Comment by Jones-S** [comment]
@FabianEllenberger Just drove mit insane... Same error
