### ISSUE TITLE
How can i make a Video Carousel ?

### ISSUE THREAD

**Issue by codeitlikemiley** [RobinCK/vue-gallery#2]
I copy your Sample It works fine , but i want a behaviour like this,
You listed all the video, you click it the youtube video appears... ( not full screen) 
then you click the youtube video to play,
without being inside the modal gallery...
How can i achieve this effect thanks for answer

**Comment by RobinCK** [comment]
@codeitlikemiley 
example for 1.2.1 release https://fiddle.jshell.net/Robin_ck/rpfmb1wq/
I hope I understood you correctly

**Comment by seyfer** [comment]
@RobinCK an example is not available anymore.
