### ISSUE TITLE
vue-gallery & fullpage.js

### ISSUE THREAD

**Issue by DigitalWheelie** [RobinCK/vue-gallery#21]
Hi,

I'm trying to get vue-gallery to work with [fullpage.js](https://alvarotrigo.com/fullPage/) and I'm having trouble.

Specifically, when I have a gallery on a page that can scroll [horizontally](https://alvarotrigo.com/fullPage/#page2), the "slides" div width is the width of all "slides", not just the one on-screen. So if my browser width is 1500px, I have three horizontal screens, then the "slides" width is 4500px instead of 1500px and images are in the center of the three slides.

I tried to create a galleryWrapper div with width: 100vw but that's not working.

Any suggestions?
Many thanks!

--Ted

**Comment by RobinCK** [comment]
Hi @DigitalWheelie 
Please create an example on jsfiddle.net

**Comment by DigitalWheelie** [comment]
I think this shows what's happening:
[https://jsfiddle.net/DigitalWheelie/1uof4n7m/29/](https://jsfiddle.net/DigitalWheelie/1uof4n7m/29/)

When you navigate to "slide 2" (swipe/scroll down) and click on a thumbnail, the enlargement loads in the center of the horizontal block of three slides, not the single slide/screen.

**Comment by DigitalWheelie** [comment]
YES! YES!
Thank you! :D
