### ISSUE TITLE
How do I integrate vue-gallery with NuxtJS?

### ISSUE THREAD

**Issue by rlam3** [RobinCK/vue-gallery#3]
How do I integrate vue-gallery with NuxtJS as a Plugin? Does it require SSR or no?

**Comment by RobinCK** [comment]
Sorry, I'm not competent in this issue, I did not work with nuxt.js

**Comment by lomholdt** [comment]
There are issues using this component when using SSR. It works without any issues if you disable SSR for this plugin. Heres how:

- Make sure you have installed the plugin using npm
- Add a new `vue-gallery.js` to your nuxt plugins folder containing the following:

```
import Vue from 'vue'
import VueGallery from 'vue-gallery'

Vue.component('gallery', VueGallery)
```

- In your `nuxt.config.js` add `{ src: '~/plugins/gallery.js', ssr: false }` to the `plugins` array.

**Comment by rlam3** [comment]
@lomholdt it's strange because it works but cannot find the widget container 

Any idea on why this may be? Thanks! 

```
blueimp Gallery: Widget container not found. #blueimp-gallery
```

**Comment by RobinCK** [comment]
@rlam3 what version of the library?

**Comment by rlam3** [comment]
@RobinCK I'm using the latest version. Thanks.

**Comment by RobinCK** [comment]
I want to note that this error was in v1.2.0 version in v1.2.1 fixed

**Comment by rlam3** [comment]
I think I found my problem. <no-ssr> tags need to be implemented between `gallery`

**Comment by rlam3** [comment]
Are there plans to also integrate a textfield in the gallery mode? It would be nice to have something to describe the images inside the gallery. Thanks!

**Comment by rlam3** [comment]
@RobinCK I took a look at blueimp and saw that they have a way to integrate a description for each image. Would it be possible that you can turn this feature on with vue-gallery? If so, how? Thanks! Really appreciate your help here.
 https://github.com/blueimp/Gallery

**Comment by JonasJW** [comment]
Thanks @lomholdt this worked but when I do it like this I get: 

`vue.runtime.esm.js:587 [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

Any Idea what this is or how to solve it?

**Comment by scottyzen** [comment]
Still can't seem to get this to work.
When my page loads I get this error `GET https://mysite.netlify.com/gallery/[object%20Object] 404` and when I click on an image this error `blueimp Gallery: Widget container not found. #blueimp-gallery`

Anyone have any ideas?

**Comment by scottyzen** [comment]
> Still can't seem to get this to work.
> When my page loads I get this error `GET https://mysite.netlify.com/gallery/[object%20Object] 404` and when I click on an image this error `blueimp Gallery: Widget container not found. #blueimp-gallery`
> 
> Anyone have any ideas?

Fixed. Turned out it was a problem with Purgecss removing class names.

**Comment by core01** [comment]
@scottyzen Hi Scott, how did you fix the problem with Purgecss and vue-gallery? I want to use vue-gallery with PurgeCSS, but the last removes all styles.

**Comment by mornir** [comment]
For anyone wondering about the necessary config for purgeCSS:
```js
purgeCSS: {
    whitelistPatternsChildren: [/^blueimp.+/],
}
```

**Comment by jasonkur** [comment]
I have added the plugins above to the nuxt.config.js but getting this error. Does anyone know why?
 ```SyntaxError
Invalid or unexpected token```

**Comment by mornir** [comment]
Did you add `.client.js` at the end of the file?
Like this https://github.com/mornir/makeup-website/blob/dev/nuxt.config.js#L54

**Comment by jasonkur** [comment]
> Did you add `.client.js` at the end of the file?
> Like this https://github.com/mornir/makeup-website/blob/dev/nuxt.config.js#L54
Yes, I tried following your files but still get the same error

```
plugins: [
    '~/ui/index.ts',
    '~/plugins/getApp.ts',
    { src: '~/plugins/swiper.ts', ssr: false },
    { src: '~/plugins/vue-gallery.client.ts', ssr: false },
  ],

**vue-gallery.client.ts**
import Vue from 'vue';
import VueGallery from 'vue-gallery';

Vue.component('VGallery', VueGallery);

**component**
import VueGallery from 'vue-gallery';

**Comment by mornir** [comment]
1. You don't need to add ssr: false
2. You shouldn't import VueGallery inside the component
Does this help solve the problem?

**Comment by jasonkur** [comment]
> 1. You don't need to add `ssr: false`
> 2. You shouldn't import VueGallery inside the component
>    Does this help solve the problem?

ahh thank you! that worked
