### ISSUE TITLE
Weird closing button

### ISSUE THREAD

**Issue by jasonmarysael** [RobinCK/vue-gallery#33]
Hi, 

For some reason i'm getting a weird closing button:

![image 303](https://user-images.githubusercontent.com/28600053/40735582-d1eb3dc6-643b-11e8-9c6e-ae7242705666.png)

When I edit the source in the browsersconsole A normal "x" is being showed:

![image 304](https://user-images.githubusercontent.com/28600053/40735772-53d27ab6-643c-11e8-9177-d9a3e192a76b.png)

Any idea what could be the cause of this? 

I'm using the latest version 1.3.5.

**Comment by RobinCK** [comment]
Thank you, I will correct in the next version
