### ISSUE TITLE
Multiple galleries on page and youtube

### ISSUE THREAD

**Issue by focussing** [RobinCK/vue-gallery#39]
I need more than one gallery entries on my page, one with a youtube video, and one with several images on another (bootstrap) row.
So I used this:
```
<div class="col-md-6">
  <gallery :images="movie1" :index="index" @close="index = null"></gallery>
  <img class="img-fluid" src="/images/thumbnail_elementary.png" alt="movie1" @click="index=0" />
</div>
```
And further down on the page:
```
<div class="col-md-6">
  <gallery :images="images" :index="index" @close="index = null"></gallery>
  <img class="img-fluid" src="/images/thumbnail_elementary.png" alt="images" @click="index=0" />
</div>
```
The js pieces:
```
images: [
    'images/si.jpg',
    'images/res1.jpg',
    'images/res2.jpg',
    'images/halite.jpg',
    'images/calcite.jpg',
    'images/TiO2.jpg',
    'images/TiO2_Rut_Ana_Main_Peaks.jpg'
],
movie1: [{
    title: 'our movie',
    href: 'https://www.youtube.com/watch?v=VIDEO_ID',
    type: 'text/html',
    youtube: 'VIDEO_ID',
}],
```
What happens is the following:
1) first time after page reload it works more or less (see #2 below), next clicks a Cross-Origin Read Blocking error occurs, the second <gallery> needs to be commented out.
2) the youtube movie is not played immediately, and when finally, not in a lightbox. 
- First a small "play" symbol occurs
- When clicked it opens a full screen youtube screen opens, showing a thumbnail
- The movie plays only when clicking the thumbnail, but not played in the lightbox but in a youtube environment.

What am i doing wrong?
Please help....

**Comment by focussing** [comment]
demo: [test.xplorex.eu](test.xplorex.eu)

**Comment by RobinCK** [comment]
Hi @focussing 

My example for your question https://jsfiddle.net/Robin_ck/93n1u4ck/
 - Multiple galleries on page
 - Youtube autoplay 

Other youtube player options: https://developers.google.com/youtube/player_parameters

**Comment by focussing** [comment]
Hello @RobinCK , thank you for your example.
I have still troubles with youtube autoplay, your example exactly resembles what I mean. You have to click several times to get it to play, and when it plays it is hard to get out via ESC.
