### ISSUE TITLE
Items are all floating left. Anyway for me to align it in the center?

### ISSUE THREAD

**Issue by rlam3** [RobinCK/vue-gallery#4]
Items are all floating left.
Which class should I be aligning in css to make the images in the center?

**Comment by RobinCK** [comment]
I did not understand the question
example https://fiddle.jshell.net/Robin_ck/LffrLb2k/show/light/ all on the center

**Comment by rlam3** [comment]
images are not center if you extend your window. 
![screen shot 2017-10-02 at 4 54 12 pm](https://user-images.githubusercontent.com/1154044/31101220-56258a54-a792-11e7-87f6-da3449220585.png)

**Comment by RobinCK** [comment]
https://fiddle.jshell.net/Robin_ck/3qmaun2a/embedded/
