### ISSUE TITLE
Nuxt.js bug

### ISSUE THREAD

**Issue by ovsw** [RobinCK/vue-gallery#61]
Using nuxt 2, latest version of vue-gallery from NPM, 

/plugins/vue-gallery.js: 
```
import Vue from 'vue'
import VueGallery from 'vue-gallery'

Vue.component('gallery', VueGallery)
```
then 
```
{ src: '~/plugins/vue-gallery.js', ssr: false }
```
Gallery is operational in **dev mode** but throws error:
```
The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
```
In **productiuon mode**, after `build` and `start`, gallery no longer operational. On click on gallery item throws error: 
```
blueimp Gallery: Widget container not found. #blueimp-gallery
```

**Comment by ovsw** [comment]
Just to clarify: only the SSR part isn't working, if I visit the gallery from another page, in production, it works.  Just on the initial  render (access  URL of the gallery page directly) it  fails as described above.

**Comment by ovsw** [comment]
Found a fix, need to wrap the vue-gallery component inside no-ssr tags. Following the example above, it wuld be like this, inside an SFC: 
```
<template>
<section>
<no-ssr>
      <gallery 
        :images="images" 
        :index="index" 
        @close="index = null"/>
    </no-ssr>

.....
```

**Comment by RobinCK** [comment]
Maybe you can help #3
