### ISSUE TITLE
Dependency errors on vue-gallery 1.5.1

### ISSUE THREAD

**Issue by jericopulvera** [RobinCK/vue-gallery#72]
These dependencies were not found:                                                                                                                                     friendly-errors 17:12:06
                                                                                                                                                                       friendly-errors 17:12:06
* vue-runtime-helpers/inject-style/browser.js in ./node_modules/vue-gallery/dist/js/vue-gallery.js                                                                     friendly-errors 17:12:06
* vue-runtime-helpers/normalize-component.js in ./node_modules/vue-gallery/dist/js/vue-gallery.js

**Comment by RobinCK** [comment]
When does this error occur?

**Comment by jericopulvera** [comment]
on npm run dev or npm run build

**Comment by RobinCK** [comment]
Everything works fine for me. [video](https://monosnap.com/file/JH9FAqyp9vLzRNpQwGvGHQd5n72C7k)

please use yarn

**Comment by jericopulvera** [comment]
I installed this on a nuxt project. Then I did an npm run dev then the error above appears.

**Comment by RobinCK** [comment]
please check vue-gallery@2.0.0
