### ISSUE TITLE
Invalid or unexpected token 

### ISSUE THREAD

**Issue by thetechguy61705** [RobinCK/vue-gallery#78]
http://www.teaspilledallover.me/i/jvza5bnt

Not sure what caused this.
I didn't change anything, it was working one second, then it stopped working the next

**Comment by bing8u** [comment]
Running in nuxt,

The mode is universal, which will report errors

``nuxt.config.js``

```
export default {
     mode: 'universal',   // 'spa' is ok
     ...
     ...
     ...
}
```

```js
SyntaxError
Invalid or unexpected token
```

**Comment by thetechguy61705** [comment]
@bing8u Thanks! :) I will close this thread now. If you have any knowledge about my other issue as well please check it out [here](https://github.com/RobinCK/vue-gallery/issues/77)
